# This file is like the recipe card for AWS CodeBuild. 
# It contains step-by-step instructions that tell CodeBuild exactly 
# how to turn your raw code into a deployable package. 
# In this project, it tells CodeBuild how to compile the Java application, 
# run any tests, and then package up everything needed for deployment.
version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8

  pre_build:
    commands:
      - echo Initializing environment
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain nextwork --domain-owner 437331089401 --region eu-north-1 --query authorizationToken --output text`

  build:
    commands:
      - echo Build started on `date`
      - mvn -s settings.xml compile
      - echo Running unit tests...
      - mvn -s settings.xml test

  post_build:
    commands:
      - echo Build completed on `date`
      - mvn -s settings.xml package

# After build the app, make sure to include these additional files in the final package.
# We're adding our appspec.yml and scripts folder because CodeDeploy will need them to properly
# deploy the application. Without them, CodeDeploy wouldn't know what to do with our compiled code!
artifacts: 
  files:
    - target/nextwork-web-project.war #Build App
    - target/surefire-reports/**/* # save test report
    - appspec.yml # 
    - scripts/**/*
  discard-paths: no

cache:
  paths:
    - '/root/.m2/**/*'